package input;

/**
 * This class implements the Detectable interface to specify a rectangular region of the screen
 * for which a ClickComponent object may generate a defined code value when interacted with.
 * 
 * @author Mac Clevinger
 *
 */

public class ClickRegionRectangle implements Detectable{

//---  Instance Variables   -------------------------------------------------------------------
	
	/** int value representing the bottom right corner's x coordinate of the specified rectangular region in an arbitrary coordinate plane*/
	private int xHigh;
	/** int value representing the top left corner's x coordinate of the specified rectangular region in an arbitrary coordinate plane*/
	private int xLow;
	/** int value representing the bottom right corner's y coordinate of the specified rectangular region in an arbitrary coordinate plane*/
	private int yHigh;
	/** int value representing the top left corner's y coordinate of the specified rectangular region in an arbitrary coordinate plane*/
	private int yLow;
	/** int value describing the code value that will be generated when this ClickRegionRectangle object is triggered*/
	private int code;
	
//---  Constructors   -------------------------------------------------------------------------
	
	/**
	 * Constructor for objects of the ClickRegionRectangle type that takes an array of integer
	 * values representing the coordinates of the top left corner (x, y) and bottom right corner
	 * (x, y), as well as the code value generated by this object when clicked.
	 * 
	 * Five int values in the array: xHigh, yHigh, xLow, yLow, code.
	 * 
	 * See other constructor for more holistic approach.
	 * 
	 * @param in - int[] object containing two coordinate positions (to specify a rectangular region) and the generated code value when triggered.
	 */
	
	public ClickRegionRectangle(int[] in) {
		xHigh = in[0];
		yHigh = in[1];
		xLow = in[2];
		yLow = in[3];
		code = in[4];
	}
	
	/**
	 * Constructor for objects of the ClickRegionRectangle type that takes in values to describe
	 * the top-left and bottom-right corners of a rectangle in an arbitrary coordinate plane (expected
	 * to be a Panel in which the origin is the top-left corner) as well as a code value that will
	 * be generated whenever this ClickRegionRectangle registers being selected.
	 * 
	 * @param lowX - int value representing the lower x coordinate of this rectangular region
	 * @param lowY - int value representing the lower y coordinate of this rectangular region
	 * @param highX - int value representing the upper x coordinate of this rectangular region
	 * @param highY - int value representing the upper y coordinate of this rectangular region
	 * @param inCode - int value describing the code value that will be generated when this ClickRegionRectangle is triggered. 
	 */
	
	public ClickRegionRectangle(int lowX, int lowY, int highX, int highY, int inCode) {
		xLow = lowX;
		yLow = lowY;
		xHigh = highX;
		yHigh = highY;
		code = inCode;
	}
	
//---  Getter Methods   -----------------------------------------------------------------------
	
	@Override
	public boolean wasClicked(int xPos, int yPos) {
		return xPos <= xHigh && xPos >= xLow && yPos <= yHigh && yPos >= yLow;
	}
	
	@Override
	public int getCode() {
		return code;
	}
	
}
