package visual.panel;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.io.File;
import java.awt.*;
import javax.imageio.ImageIO;
import input.Detectable;
import visual.panel.element.*;

/**
 * This class implements the Panel abstract class to provide a suite of drawing tools and interactivity
 * to the programmer via the element package, as well as handling some low-level issues that arise.
 * 
 * @author Mac Clevinger
 *
 */

public class ElementPanel extends Panel{

//---  Instance Variables   -------------------------------------------------------------------
	
	/** HashMap that saves the image associated to the provided file path and allows re-access via the file path*/
	private HashMap<String, Image> images;
	/** HashMap that assigns a name to objects that can be drawn to the screen; each repaint uses this list to draw to the screen*/
	private HashMap<String, Element> drawList;
	/** HashMap that assigns a name to defined regions of the screen that generate a specified code upon interaction*/
	private HashMap<String, Detectable> clickList;
	/** Clickable object representing the most recently selected interactive Element by the User for directing Key Inputs towards*/
	private Clickable focusElement;

//---  Constructors   -------------------------------------------------------------------------
	
	/**
	 * Constructor for objects of the ElementPanel type that uses the Panel abstract class' initiate()
	 * method and initializes the storage of Element and Image objects.
	 * 
	 * @param x - int value representing the x coordinate of this ElementPanel object's origin in its containing Frame
	 * @param y - int value representing the y coordinate of this ElementPanel object's origin in its containing Frame
	 * @param width - int value representing the width of this ElementPanel object
	 * @param height - int value representing the height of this ElementPanel object
	 */
	
	public ElementPanel(int x, int y, int width, int height){
		super();
		initiate(x, y, width, height);
		images = new HashMap<String, Image>();
		drawList = new HashMap<String, Element>();
		clickList = new HashMap<String, Detectable>();
	}
	
//---  Operations   ---------------------------------------------------------------------------

	/**
	 * Certain UI Elements have behavior that requires a communication between higher-level
	 * objects, so that is handled before the clickBehaviour() method which the programmer
	 * can overwrite to define the interactive behavior of this Panel.
	 * 
	 */
	
	public void clickEvent(int event){
		focusElement = null;
		top:
		for(Detectable d : clickList.values()) {
			if(d.getCode() == event) {
				for(String s : drawList.keySet()) {
					if(clickList.get(s) != null && clickList.get(s).equals(d)) {
						focusElement = (Clickable)drawList.get(s);
						break top;
					}
				}
			}
		}
		clickBehaviour(event);
	}
	
	/**
	 * This method exists to be overwritten on an object-by-object basis by the programmer
	 * to define the interactive behavior of this ElementPanel object.
	 * 
	 * @param event - int value representing the code generated by user interaction (mouse click on region of screen)
	 */
	
	public void clickBehaviour(int event) {
		System.out.println("Overwrite this method");
	}
	
	/**
	 * Certain UI Elements have behavior that requires a communication between higher-level
	 * objects, so that is handled before the keyBehaviour() method which the programmer
	 * can overwrite to define the interactive behavior of this Panel.
	 * 
	 */
	
	public void keyEvent(char event){
		if(focusElement != null) {
			if(!focusElement.focusEvent(event)) {
				return;
			}
		}
		keyBehaviour(event);
	}
	
	/**
	 * This method exists to be overwritten on an object-by-object basis by the programmer
	 * to define the interactive behavior of this ElementPanel object.
	 * 
	 * @param event - char value representing the key that the user pressed
	 */
	
	public void keyBehaviour(char event) {
		System.out.println("Overwrite this method");
	}
	
	public void paintComponent(Graphics g) {
		ArrayList<Element> elements = new ArrayList<Element>(drawList.values());
		Collections.sort(elements);
		for(Element d : elements) {
			d.drawToScreen(g);
		}
	}
	
	/**
	 * This method reassigns the regions of the screen that detect user input and
	 * trigger a clickEvent() with the corresponding generated code value.
	 * 
	 * It first removes all Detection regions from this ElementPanel, and then calls
	 * on all Clickable objects to generate their Detectable click regions to be added
	 * to this ElementPanel. 
	 * 
	 */
	
	public void updateClickRegions() {
		resetDetectionRegions();
		for(Detectable d : clickList.values()) {
			if(!addClickRegion(d)) {
				removeClickRegion(d.getCode());
				addClickRegion(d);
			}
		}
	}

//---  Getter Methods   -----------------------------------------------------------------------

	/**
	 * This method requests one of the Elements attributed to this ElementPanel to be returned,
	 * defined by the provided String object representing a name associated to that Element.
	 * 
	 * @param name - String object representing the name of the Element being requested.
	 * @return - Returns an Element object specified by a provided name
	 */
	
	public Element getElement(String name) {
		return drawList.get(name);
	}
	
	/**
	 * 
	 * 
	 * @param name
	 * @return
	 */
	
	public String getElementStoredText(String name) {
		try {
			return ((TextStorage)drawList.get(name)).getText();
		}
		catch(Exception e) {
			System.out.println("Illegal Cast Exception; Element object was not of type TextStorage");
			return "";
		}
	}
	
//---  Mechanics   ----------------------------------------------------------------------------
	
	public Image retrieveImage(String pathIn) {
		String path = pathIn.replace("\\", "/");
		try {
			if(images.get(path) == null) {
				images.put(path, ImageIO.read(ElementPanel.class.getResource(path.substring(path.indexOf("/")))));
			}
			return images.get(path);
		}
		catch(Exception e) {
			try {
				if(images.get(path) == null) {
					images.put(path, ImageIO.read(new File(path)));
				}
				return images.get(path);
			}
			catch(Exception e1) {
				e1.printStackTrace();
				return null;
			}
		}
	}
	
//---  Draw   ---------------------------------------------------------------------------------
	
	//-- Image  -----------------------------------------------
	
	public void addImage(String name, int priority, int x, int y, String path){
		drawList.put(name, new DrawnImage(x, y, retrieveImage(path)));
	}
	
	public void addImage(String name, int priority, int x, int y, String path, int scale){
		drawList.put(name, new DrawnImage(x, y, priority, retrieveImage(path), scale));
	}
	
	//-- Button  ----------------------------------------------
	
	public void addButton(String name, int priority, int x, int y, int wid, int hei, Color col, int key){
		DrawnButton drawn = new DrawnButton(x, y, priority, wid, hei, key, col);
		drawList.put(name, drawn);
		clickList.put(name, drawn.getDetectionRegion());
		updateClickRegions();
	}
	
	public void addImageButton(String name, int priority, int x, int y, String path, int key){
		DrawnImageButton but = new DrawnImageButton(x, y, priority, retrieveImage(path), key);
		drawList.put(name, but);
		clickList.put(name, but.getDetectionRegion());
		updateClickRegions();
	}
	
	public void addImageButton(String name, int priority, int x, int y, String path, int key, int scale){
		DrawnImageButton but = new DrawnImageButton(x, y, priority, retrieveImage(path), key, scale);
		drawList.put(name, but);
		clickList.put(name, but.getDetectionRegion());
		updateClickRegions();
	}
	
	//-- Text  ------------------------------------------------
	
	public void addText(String name, int priority, int x, int y, String phrase, Font font){
		DrawnText text = new DrawnText(x, y, priority, phrase, font);
		drawList.put(name, text);
	}

	public void addTextEntry(String name, int priority, int x, int y, int width, int height, int code, Font font) {
		DrawnTextArea dTA = new DrawnTextArea(x, y, x + width, y + height, priority, code, font);
		drawList.put(name, dTA);
		clickList.put(name,  dTA.getDetectionRegion());
		updateClickRegions();
	}
	
	//-- Shapes  ----------------------------------------------
	
	public void addRectangle(String name, int priority, int x, int y, int width, int height, Color col) {
		DrawnRectangle rect = new DrawnRectangle(x, y, x + width, y + height, priority, col);
		drawList.put(name, rect);
	}
	
	public void addRectangle(String name, int priority, int x, int y, int width, int height, Color fillColor, Color borderColor) {
		DrawnRectangle rect = new DrawnRectangle(x, y, x + width, y + height, priority, fillColor, borderColor);
		drawList.put(name, rect);
	}

//---  Remove Elements   ----------------------------------------------------------------------
	
	public void removeElement(String name) {
		//More
		updateClickRegions();
	}
	
}
