package input;

public interface EventReceiver {
	
//---  Operations   ---------------------------------------------------------------------------
	
	//-- Mouse Input  -----------------------------------------
	
	/**
	 * This method is triggered whenever the Panel object detects user interaction
	 * via the Mouse; exact implementation of response is left to the implementation
	 * of the Panel abstract class (or left to the creation of an object of that class
	 * by overriding this method or others to tailor-fit behavior to different Panels.)
	 * 
	 * @param event - int value representing the code generated by the user's action (-1 by default represents no object was selected)
	 */
	
	public abstract void clickEvent(int event, int x, int y, int clickType);
	
	public abstract void clickReleaseEvent(int event, int x, int y, int clickType);
	
	public abstract void clickPressEvent(int event, int x, int y, int clickType);
	
	public abstract void dragEvent(int event, int x, int y, int clickType);
	
	public abstract void mouseMoveEvent(int event, int x, int y);

	//-- Mouse Wheel Input  -----------------------------------
	
	public abstract void mouseWheelEvent(int rotation);
	
	//-- Key Input  -------------------------------------------
	
	/**
	 * This method is triggered whenever the Panel object detects user interaction
	 * via the KeyBoard; exact implementation of response is left to the implementation
	 * of the Panel abstract class (or left to the creation of an object of that class
	 * by overriding this method or others to tailor-fit behavior to different Panels.)
	 * 
	 * @param event - char value representing which key was pressed by the user; special keys may generate strange values.
	 */
	
	public abstract void keyEvent(char event);
	
	public abstract void keyPressEvent(char event);
	
	public abstract void keyReleaseEvent(char event);

}
