package input;

import java.awt.Component;

public interface EventReceiver {
	
	/**
	 * This method is triggered whenever the Panel object detects user interaction
	 * via the Mouse; exact implementation of response is left to the implementation
	 * of the Panel abstract class (or left to the creation of an object of that class
	 * by overriding this method or others to tailor-fit behavior to different Panels.)
	 * 
	 * @param event - int value representing the code generated by the user's action (-1 by default represents no object was selected)
	 */
	
	public abstract void clickEvent(int event, int x, int y);
	
	public abstract void clickReleaseEvent(int event, int x, int y);
	
	public abstract void clickPressEvent(int event, int x, int y);
	
	public abstract void dragEvent(int event, int x, int y);
	
	public abstract void mouseWheelEvent(int rotation);
	
	public abstract void mouseMoveEvent(int x, int y);
	
	/**
	 * This method is triggered whenever the Panel object detects user interaction
	 * via the KeyBoard; exact implementation of response is left to the implementation
	 * of the Panel abstract class (or left to the creation of an object of that class
	 * by overriding this method or others to tailor-fit behavior to different Panels.)
	 * 
	 * @param event - char value representing which key was pressed by the user; special keys may generate strange values.
	 */
	
	public abstract void keyEvent(char event);
	
	public abstract void requestFocusInWindow();
	
	public abstract Component getListenerRecipient();
	
}
